spring:
  datasource:
    url: jdbc:jdbc:postgresql://db.mmzuziugljgphxmpchds.supabase.co:5432/postgres
    username: postgres
    password: NtcAn2jb4YI6GdAP
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect